version: 0.2

phases:
  install:
    commands:
      - echo do nothing...
  pre_build:
    commands:
      - echo run unittests om `date`
      - make test
  build:
    commands:
      - echo Build started on `date`
      - make dist
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - dist/aws-cicd-0.1.0.tar.gz
    - cd/cf-vpc.yaml
    - cd/cf-vpc-dev-configs.json
    - cd/cf-ec2.yaml
    - cd/cf-ec2-dev-configs.json
