version: 0.2

phases:
  install:
    commands:
      - echo print out CODEBUILD vars...
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo $CODEBUILD_SOURCE_VERSION
  pre_build:
    commands:
      - echo run unittests om `date`
      - python setup.py test
  build:
    commands:
      - echo Build started on `date`
      - python setup.py sdist
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - dist/aws-cicd-0.1.0.tar.gz
    - cf-vpc.yaml
    - cf-vpc-dev-configs.json
    - cf-ec2.yaml
    - cf-ec2-dev-configs.json
