AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A very simple RESTful API service based on API gateway + Lambda functions and CloudWatch monitorings
Parameters:
  SecretName:
    Description: Secret name stored in SSM parameter store
    Type: String
  APIP95LatencyAlarmThreshold:
    Description: p95 Latency alarm threshold (Milliseconds)
    Type: Number
    Default: 10000
  AlarmEmail:
    Description: Alarm email
    Type: String
  APIStageName:
    Description: API Stage Name
    Type: String
    Default: prod

Globals:
  Function:
    Runtime: python2.7
    Handler: main.handler
    Timeout: 20
Resources:
  HomeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../dist/api_home-0.1.0.zip
      Policies: AWSLambdaVPCAccessExecutionRole
      Events:
        Home:
          Type: Api
          Properties:
            Path: /
            Method: get
            RestApiId: !Ref Api

  SecretFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: KMSKeyDecryption
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              -
                Effect: Allow
                Action: kms:Decrypt
                Resource: '*'
        - PolicyName: SSMGetParameters
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              -
                Effect: Allow
                Action:
                  - ssm:GetParameter
                  - ssm:GetParameters
                Resource: '*'

  SecretFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../dist/api_secret-0.1.0.zip
      Role: !GetAtt SecretFunctionRole.Arn
      Environment:
        Variables:
          SECRET_NAME: !Ref SecretName
          REGION: !Ref AWS::Region
      Events:
        Secret:
          Type: Api
          Properties:
            Path: /secret
            Method: get
            RestApiId: !Ref Api

  SleepFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../dist/api_sleep-0.1.0.zip
      Policies: AWSLambdaVPCAccessExecutionRole
      Events:
        Sleep:
          Type: Api
          Properties:
            Path: /sleep/{secs}
            Method: get
            RestApiId: !Ref Api

  HealthCheckFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../dist/api_healthcheck-0.1.0.zip
      Policies: AWSLambdaVPCAccessExecutionRole
      Events:
        HealthCheck:
          Type: Api
          Properties:
            Path: /healthcheck
            Method: get
            RestApiId: !Ref Api
  Api:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub ${AWS::StackName}-api
      StageName: !Ref APIStageName
      DefinitionBody:
        swagger: '2.0'
        info:
          version: 1.0.0
          title: Simple API services
        basePath: /
        schemes:
          - https
        consumes:
          - application/json
        produces:
          - application/json
        paths:
          '/sleep/{secs}':
            get:
              description: sleep API
              produces:
                - application/json
              parameters:
                - name: secs
                  in: path
                  required: true
                  description: How long the api to sleep
                  type: string
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                passthroughBehavior: "when_no_match"
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SleepFunction.Arn}/invocations
              responses:
                '200':
                  description: Sleep response
                  schema:
                    type: string
          '/healthcheck':
            get:
              description: healthcheck for API services
              produces:
                - application/json
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                passthroughBehavior: "when_no_match"
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${HealthCheckFunction.Arn}/invocations
              responses:
                '200':
                  description: healthcheck OK
                  schema:
                    type: string
          '/secret':
            get:
              description: get secret info. API
              produces:
                - application/json
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                passthroughBehavior: "when_no_match"
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SecretFunction.Arn}/invocations
              responses:
                '200':
                  description: healthcheck OK
                  schema:
                    type: string
          '/':
            get:
              description: service home page
              produces:
                - application/json
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                passthroughBehavior: "when_no_match"
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${HomeFunction.Arn}/invocations
              responses:
                '200':
                  description: home page OK
                  schema:
                    type: string

  AlarmSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        -
          Endpoint: !Ref AlarmEmail
          Protocol: email
      DisplayName: !Sub ${AWS::StackName}-Topic

  ALBP95LatencyAlarm:
    DependsOn:
      - AlarmSNSTopic
      - Api
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: !Sub "Alarm for API p95 latency > ${APIP95LatencyAlarmThreshold} Milliseconds"
      Namespace: AWS/ApiGateway
      MetricName: Latency
      Dimensions:
        - Name: ApiName
          Value: !Sub ${AWS::StackName}-api
        - Name: Stage
          Value: !Ref APIStageName
      ExtendedStatistic: p95
      Period: 60
      EvaluationPeriods: 1
      Threshold: !Ref APIP95LatencyAlarmThreshold
      ComparisonOperator: GreaterThanThreshold
      AlarmActions:
        - !Ref AlarmSNSTopic
      OKActions:
        - !Ref AlarmSNSTopic
      TreatMissingData: notBreaching
      Unit: Milliseconds

  Dashboard:
    Type: AWS::CloudWatch::Dashboard
    DependsOn: Api
    Properties:
      DashboardName: !Sub ${AWS::StackName}-dashboard
      DashboardBody: !Sub
        - |
          {
            "widgets": [
              {
                "type": "metric",
                "x": 0,
                "y": 0,
                "width": 12,
                "height": 6,
                "properties": {
                  "metrics": [
                    [
                      "AWS/ApiGateway",
                      "Latency",
                      "ApiName",
                      "${APIName}",
                      "Stage",
                      "${APIStageName}"
                    ]
                  ],
                  "period": 60,
                  "stat": "p95",
                  "region": "${AWS::Region}",
                  "title": "API P95 Response time"
                }
              }
            ]
          }
        - {'APIName': !Sub '${AWS::StackName}-api'}

Outputs:
  APIGatewayURL:
    Value: !Sub https://${Api}.execute-api.${AWS::Region}.amazonaws.com/prod